kind: pipeline
type: kubernetes
name: default

workspace:
  base: /drone/src
  path: .

steps:
  - name: lint
    image: python:3.11-slim
    commands:
      - pip install --no-cache-dir black
      - black --check .

  - name: test
    image: python:3.11-slim
    commands:
      - pip install --no-cache-dir pytest
      - pytest -q

  - name: run
    image: python:3.11-slim
    commands:
      - python hello.py

