kind: pipeline
type: kubernetes
name: default

workspace:
  base: /drone/src
  path: .

steps:
  - name: lint
    image: python:3.11-slim
    commands:
      - pip install black
      - black --check .

  - name: run
    image: python:3.11-slim
    commands:
      - python hello.py
