kind: pipeline
type: kubernetes
name: patch-build

trigger:
  branch:
    - patch-*

steps:
  - name: lint
    image: node:20
    commands:
      - npm ci
      - npm run lint

  - name: test
    image: node:20
    commands:
      - npm test

  - name: build 
    image: node:20
    commands:
      - npm run build
